// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school.proto

package uc.mei.is.ProtocolBufferClasses;

/**
 * Protobuf type {@code model.ProtoSchool}
 */
public final class ProtoSchool extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.ProtoSchool)
    ProtoSchoolOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoSchool.newBuilder() to construct.
  private ProtoSchool(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoSchool() {
    professors_ = java.util.Collections.emptyList();
    students_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoSchool();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoSchool(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              professors_ = new java.util.ArrayList<uc.mei.is.ProtocolBufferClasses.ProtoProfessor>();
              mutable_bitField0_ |= 0x00000001;
            }
            professors_.add(
                input.readMessage(uc.mei.is.ProtocolBufferClasses.ProtoProfessor.PARSER, extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              students_ = new java.util.ArrayList<uc.mei.is.ProtocolBufferClasses.ProtoStudent>();
              mutable_bitField0_ |= 0x00000002;
            }
            students_.add(
                input.readMessage(uc.mei.is.ProtocolBufferClasses.ProtoStudent.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        professors_ = java.util.Collections.unmodifiableList(professors_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        students_ = java.util.Collections.unmodifiableList(students_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uc.mei.is.ProtocolBufferClasses.ProtocolBufferClasses.internal_static_model_ProtoSchool_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uc.mei.is.ProtocolBufferClasses.ProtocolBufferClasses.internal_static_model_ProtoSchool_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uc.mei.is.ProtocolBufferClasses.ProtoSchool.class, uc.mei.is.ProtocolBufferClasses.ProtoSchool.Builder.class);
  }

  public static final int PROFESSORS_FIELD_NUMBER = 1;
  private java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoProfessor> professors_;
  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  @java.lang.Override
  public java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoProfessor> getProfessorsList() {
    return professors_;
  }
  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends uc.mei.is.ProtocolBufferClasses.ProtoProfessorOrBuilder> 
      getProfessorsOrBuilderList() {
    return professors_;
  }
  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  @java.lang.Override
  public int getProfessorsCount() {
    return professors_.size();
  }
  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  @java.lang.Override
  public uc.mei.is.ProtocolBufferClasses.ProtoProfessor getProfessors(int index) {
    return professors_.get(index);
  }
  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  @java.lang.Override
  public uc.mei.is.ProtocolBufferClasses.ProtoProfessorOrBuilder getProfessorsOrBuilder(
      int index) {
    return professors_.get(index);
  }

  public static final int STUDENTS_FIELD_NUMBER = 2;
  private java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoStudent> students_;
  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  @java.lang.Override
  public java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoStudent> getStudentsList() {
    return students_;
  }
  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends uc.mei.is.ProtocolBufferClasses.ProtoStudentOrBuilder> 
      getStudentsOrBuilderList() {
    return students_;
  }
  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  @java.lang.Override
  public int getStudentsCount() {
    return students_.size();
  }
  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  @java.lang.Override
  public uc.mei.is.ProtocolBufferClasses.ProtoStudent getStudents(int index) {
    return students_.get(index);
  }
  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  @java.lang.Override
  public uc.mei.is.ProtocolBufferClasses.ProtoStudentOrBuilder getStudentsOrBuilder(
      int index) {
    return students_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getProfessorsCount(); i++) {
      if (!getProfessors(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getStudentsCount(); i++) {
      if (!getStudents(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < professors_.size(); i++) {
      output.writeMessage(1, professors_.get(i));
    }
    for (int i = 0; i < students_.size(); i++) {
      output.writeMessage(2, students_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < professors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, professors_.get(i));
    }
    for (int i = 0; i < students_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, students_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uc.mei.is.ProtocolBufferClasses.ProtoSchool)) {
      return super.equals(obj);
    }
    uc.mei.is.ProtocolBufferClasses.ProtoSchool other = (uc.mei.is.ProtocolBufferClasses.ProtoSchool) obj;

    if (!getProfessorsList()
        .equals(other.getProfessorsList())) return false;
    if (!getStudentsList()
        .equals(other.getStudentsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProfessorsCount() > 0) {
      hash = (37 * hash) + PROFESSORS_FIELD_NUMBER;
      hash = (53 * hash) + getProfessorsList().hashCode();
    }
    if (getStudentsCount() > 0) {
      hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
      hash = (53 * hash) + getStudentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uc.mei.is.ProtocolBufferClasses.ProtoSchool prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.ProtoSchool}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.ProtoSchool)
      uc.mei.is.ProtocolBufferClasses.ProtoSchoolOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uc.mei.is.ProtocolBufferClasses.ProtocolBufferClasses.internal_static_model_ProtoSchool_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uc.mei.is.ProtocolBufferClasses.ProtocolBufferClasses.internal_static_model_ProtoSchool_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uc.mei.is.ProtocolBufferClasses.ProtoSchool.class, uc.mei.is.ProtocolBufferClasses.ProtoSchool.Builder.class);
    }

    // Construct using uc.mei.is.ProtocolBufferClasses.ProtoSchool.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProfessorsFieldBuilder();
        getStudentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (professorsBuilder_ == null) {
        professors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        professorsBuilder_.clear();
      }
      if (studentsBuilder_ == null) {
        students_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        studentsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uc.mei.is.ProtocolBufferClasses.ProtocolBufferClasses.internal_static_model_ProtoSchool_descriptor;
    }

    @java.lang.Override
    public uc.mei.is.ProtocolBufferClasses.ProtoSchool getDefaultInstanceForType() {
      return uc.mei.is.ProtocolBufferClasses.ProtoSchool.getDefaultInstance();
    }

    @java.lang.Override
    public uc.mei.is.ProtocolBufferClasses.ProtoSchool build() {
      uc.mei.is.ProtocolBufferClasses.ProtoSchool result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uc.mei.is.ProtocolBufferClasses.ProtoSchool buildPartial() {
      uc.mei.is.ProtocolBufferClasses.ProtoSchool result = new uc.mei.is.ProtocolBufferClasses.ProtoSchool(this);
      int from_bitField0_ = bitField0_;
      if (professorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          professors_ = java.util.Collections.unmodifiableList(professors_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.professors_ = professors_;
      } else {
        result.professors_ = professorsBuilder_.build();
      }
      if (studentsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          students_ = java.util.Collections.unmodifiableList(students_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.students_ = students_;
      } else {
        result.students_ = studentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uc.mei.is.ProtocolBufferClasses.ProtoSchool) {
        return mergeFrom((uc.mei.is.ProtocolBufferClasses.ProtoSchool)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uc.mei.is.ProtocolBufferClasses.ProtoSchool other) {
      if (other == uc.mei.is.ProtocolBufferClasses.ProtoSchool.getDefaultInstance()) return this;
      if (professorsBuilder_ == null) {
        if (!other.professors_.isEmpty()) {
          if (professors_.isEmpty()) {
            professors_ = other.professors_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProfessorsIsMutable();
            professors_.addAll(other.professors_);
          }
          onChanged();
        }
      } else {
        if (!other.professors_.isEmpty()) {
          if (professorsBuilder_.isEmpty()) {
            professorsBuilder_.dispose();
            professorsBuilder_ = null;
            professors_ = other.professors_;
            bitField0_ = (bitField0_ & ~0x00000001);
            professorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProfessorsFieldBuilder() : null;
          } else {
            professorsBuilder_.addAllMessages(other.professors_);
          }
        }
      }
      if (studentsBuilder_ == null) {
        if (!other.students_.isEmpty()) {
          if (students_.isEmpty()) {
            students_ = other.students_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStudentsIsMutable();
            students_.addAll(other.students_);
          }
          onChanged();
        }
      } else {
        if (!other.students_.isEmpty()) {
          if (studentsBuilder_.isEmpty()) {
            studentsBuilder_.dispose();
            studentsBuilder_ = null;
            students_ = other.students_;
            bitField0_ = (bitField0_ & ~0x00000002);
            studentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentsFieldBuilder() : null;
          } else {
            studentsBuilder_.addAllMessages(other.students_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getProfessorsCount(); i++) {
        if (!getProfessors(i).isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getStudentsCount(); i++) {
        if (!getStudents(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uc.mei.is.ProtocolBufferClasses.ProtoSchool parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uc.mei.is.ProtocolBufferClasses.ProtoSchool) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoProfessor> professors_ =
      java.util.Collections.emptyList();
    private void ensureProfessorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        professors_ = new java.util.ArrayList<uc.mei.is.ProtocolBufferClasses.ProtoProfessor>(professors_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.ProtocolBufferClasses.ProtoProfessor, uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder, uc.mei.is.ProtocolBufferClasses.ProtoProfessorOrBuilder> professorsBuilder_;

    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoProfessor> getProfessorsList() {
      if (professorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(professors_);
      } else {
        return professorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public int getProfessorsCount() {
      if (professorsBuilder_ == null) {
        return professors_.size();
      } else {
        return professorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoProfessor getProfessors(int index) {
      if (professorsBuilder_ == null) {
        return professors_.get(index);
      } else {
        return professorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public Builder setProfessors(
        int index, uc.mei.is.ProtocolBufferClasses.ProtoProfessor value) {
      if (professorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfessorsIsMutable();
        professors_.set(index, value);
        onChanged();
      } else {
        professorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public Builder setProfessors(
        int index, uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder builderForValue) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        professors_.set(index, builderForValue.build());
        onChanged();
      } else {
        professorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public Builder addProfessors(uc.mei.is.ProtocolBufferClasses.ProtoProfessor value) {
      if (professorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfessorsIsMutable();
        professors_.add(value);
        onChanged();
      } else {
        professorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public Builder addProfessors(
        int index, uc.mei.is.ProtocolBufferClasses.ProtoProfessor value) {
      if (professorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfessorsIsMutable();
        professors_.add(index, value);
        onChanged();
      } else {
        professorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public Builder addProfessors(
        uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder builderForValue) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        professors_.add(builderForValue.build());
        onChanged();
      } else {
        professorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public Builder addProfessors(
        int index, uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder builderForValue) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        professors_.add(index, builderForValue.build());
        onChanged();
      } else {
        professorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public Builder addAllProfessors(
        java.lang.Iterable<? extends uc.mei.is.ProtocolBufferClasses.ProtoProfessor> values) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, professors_);
        onChanged();
      } else {
        professorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public Builder clearProfessors() {
      if (professorsBuilder_ == null) {
        professors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        professorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public Builder removeProfessors(int index) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        professors_.remove(index);
        onChanged();
      } else {
        professorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder getProfessorsBuilder(
        int index) {
      return getProfessorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoProfessorOrBuilder getProfessorsOrBuilder(
        int index) {
      if (professorsBuilder_ == null) {
        return professors_.get(index);  } else {
        return professorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public java.util.List<? extends uc.mei.is.ProtocolBufferClasses.ProtoProfessorOrBuilder> 
         getProfessorsOrBuilderList() {
      if (professorsBuilder_ != null) {
        return professorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(professors_);
      }
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder addProfessorsBuilder() {
      return getProfessorsFieldBuilder().addBuilder(
          uc.mei.is.ProtocolBufferClasses.ProtoProfessor.getDefaultInstance());
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder addProfessorsBuilder(
        int index) {
      return getProfessorsFieldBuilder().addBuilder(
          index, uc.mei.is.ProtocolBufferClasses.ProtoProfessor.getDefaultInstance());
    }
    /**
     * <code>repeated .model.ProtoProfessor professors = 1;</code>
     */
    public java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder> 
         getProfessorsBuilderList() {
      return getProfessorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.ProtocolBufferClasses.ProtoProfessor, uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder, uc.mei.is.ProtocolBufferClasses.ProtoProfessorOrBuilder> 
        getProfessorsFieldBuilder() {
      if (professorsBuilder_ == null) {
        professorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            uc.mei.is.ProtocolBufferClasses.ProtoProfessor, uc.mei.is.ProtocolBufferClasses.ProtoProfessor.Builder, uc.mei.is.ProtocolBufferClasses.ProtoProfessorOrBuilder>(
                professors_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        professors_ = null;
      }
      return professorsBuilder_;
    }

    private java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoStudent> students_ =
      java.util.Collections.emptyList();
    private void ensureStudentsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        students_ = new java.util.ArrayList<uc.mei.is.ProtocolBufferClasses.ProtoStudent>(students_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.ProtocolBufferClasses.ProtoStudent, uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder, uc.mei.is.ProtocolBufferClasses.ProtoStudentOrBuilder> studentsBuilder_;

    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoStudent> getStudentsList() {
      if (studentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(students_);
      } else {
        return studentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public int getStudentsCount() {
      if (studentsBuilder_ == null) {
        return students_.size();
      } else {
        return studentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoStudent getStudents(int index) {
      if (studentsBuilder_ == null) {
        return students_.get(index);
      } else {
        return studentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public Builder setStudents(
        int index, uc.mei.is.ProtocolBufferClasses.ProtoStudent value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.set(index, value);
        onChanged();
      } else {
        studentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public Builder setStudents(
        int index, uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public Builder addStudents(uc.mei.is.ProtocolBufferClasses.ProtoStudent value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.add(value);
        onChanged();
      } else {
        studentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public Builder addStudents(
        int index, uc.mei.is.ProtocolBufferClasses.ProtoStudent value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.add(index, value);
        onChanged();
      } else {
        studentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public Builder addStudents(
        uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.add(builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public Builder addStudents(
        int index, uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public Builder addAllStudents(
        java.lang.Iterable<? extends uc.mei.is.ProtocolBufferClasses.ProtoStudent> values) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, students_);
        onChanged();
      } else {
        studentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public Builder clearStudents() {
      if (studentsBuilder_ == null) {
        students_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        studentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public Builder removeStudents(int index) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.remove(index);
        onChanged();
      } else {
        studentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder getStudentsBuilder(
        int index) {
      return getStudentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoStudentOrBuilder getStudentsOrBuilder(
        int index) {
      if (studentsBuilder_ == null) {
        return students_.get(index);  } else {
        return studentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public java.util.List<? extends uc.mei.is.ProtocolBufferClasses.ProtoStudentOrBuilder> 
         getStudentsOrBuilderList() {
      if (studentsBuilder_ != null) {
        return studentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(students_);
      }
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder addStudentsBuilder() {
      return getStudentsFieldBuilder().addBuilder(
          uc.mei.is.ProtocolBufferClasses.ProtoStudent.getDefaultInstance());
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder addStudentsBuilder(
        int index) {
      return getStudentsFieldBuilder().addBuilder(
          index, uc.mei.is.ProtocolBufferClasses.ProtoStudent.getDefaultInstance());
    }
    /**
     * <code>repeated .model.ProtoStudent students = 2;</code>
     */
    public java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder> 
         getStudentsBuilderList() {
      return getStudentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.ProtocolBufferClasses.ProtoStudent, uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder, uc.mei.is.ProtocolBufferClasses.ProtoStudentOrBuilder> 
        getStudentsFieldBuilder() {
      if (studentsBuilder_ == null) {
        studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            uc.mei.is.ProtocolBufferClasses.ProtoStudent, uc.mei.is.ProtocolBufferClasses.ProtoStudent.Builder, uc.mei.is.ProtocolBufferClasses.ProtoStudentOrBuilder>(
                students_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        students_ = null;
      }
      return studentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.ProtoSchool)
  }

  // @@protoc_insertion_point(class_scope:model.ProtoSchool)
  private static final uc.mei.is.ProtocolBufferClasses.ProtoSchool DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uc.mei.is.ProtocolBufferClasses.ProtoSchool();
  }

  public static uc.mei.is.ProtocolBufferClasses.ProtoSchool getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ProtoSchool>
      PARSER = new com.google.protobuf.AbstractParser<ProtoSchool>() {
    @java.lang.Override
    public ProtoSchool parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoSchool(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoSchool> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoSchool> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uc.mei.is.ProtocolBufferClasses.ProtoSchool getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

