// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school.proto

package uc.mei.is.ProtocolBufferClasses;

public interface ProtoSchoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ProtoSchool)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoProfessor> 
      getProfessorsList();
  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  uc.mei.is.ProtocolBufferClasses.ProtoProfessor getProfessors(int index);
  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  int getProfessorsCount();
  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  java.util.List<? extends uc.mei.is.ProtocolBufferClasses.ProtoProfessorOrBuilder> 
      getProfessorsOrBuilderList();
  /**
   * <code>repeated .model.ProtoProfessor professors = 1;</code>
   */
  uc.mei.is.ProtocolBufferClasses.ProtoProfessorOrBuilder getProfessorsOrBuilder(
      int index);

  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  java.util.List<uc.mei.is.ProtocolBufferClasses.ProtoStudent> 
      getStudentsList();
  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  uc.mei.is.ProtocolBufferClasses.ProtoStudent getStudents(int index);
  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  int getStudentsCount();
  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  java.util.List<? extends uc.mei.is.ProtocolBufferClasses.ProtoStudentOrBuilder> 
      getStudentsOrBuilderList();
  /**
   * <code>repeated .model.ProtoStudent students = 2;</code>
   */
  uc.mei.is.ProtocolBufferClasses.ProtoStudentOrBuilder getStudentsOrBuilder(
      int index);
}
