// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school.proto

package uc.mei.is.ProtocolBufferClasses;

public interface ProtoStudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ProtoStudent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>required string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required string telephone = 3;</code>
   * @return Whether the telephone field is set.
   */
  boolean hasTelephone();
  /**
   * <code>required string telephone = 3;</code>
   * @return The telephone.
   */
  java.lang.String getTelephone();
  /**
   * <code>required string telephone = 3;</code>
   * @return The bytes for telephone.
   */
  com.google.protobuf.ByteString
      getTelephoneBytes();

  /**
   * <code>required string gender = 4;</code>
   * @return Whether the gender field is set.
   */
  boolean hasGender();
  /**
   * <code>required string gender = 4;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <code>required string gender = 4;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>required string birthDate = 5;</code>
   * @return Whether the birthDate field is set.
   */
  boolean hasBirthDate();
  /**
   * <code>required string birthDate = 5;</code>
   * @return The birthDate.
   */
  java.lang.String getBirthDate();
  /**
   * <code>required string birthDate = 5;</code>
   * @return The bytes for birthDate.
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>required string registrationDate = 6;</code>
   * @return Whether the registrationDate field is set.
   */
  boolean hasRegistrationDate();
  /**
   * <code>required string registrationDate = 6;</code>
   * @return The registrationDate.
   */
  java.lang.String getRegistrationDate();
  /**
   * <code>required string registrationDate = 6;</code>
   * @return The bytes for registrationDate.
   */
  com.google.protobuf.ByteString
      getRegistrationDateBytes();

  /**
   * <code>required string address = 7;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>required string address = 7;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>required string address = 7;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>optional string professor = 8;</code>
   * @return Whether the professor field is set.
   */
  boolean hasProfessor();
  /**
   * <code>optional string professor = 8;</code>
   * @return The professor.
   */
  java.lang.String getProfessor();
  /**
   * <code>optional string professor = 8;</code>
   * @return The bytes for professor.
   */
  com.google.protobuf.ByteString
      getProfessorBytes();
}
